In [2]:
import pandas as pd
import numpy as np
from sklearn.covariance import EmpiricalCovariance, MinCovDet
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("https://goz39a.s3.eu-central-1.amazonaws.com/breastcancer.csv")

In [4]:
df.dropna(how='any', inplace=True)

In [5]:
df.head()

Id  Cl.thickness  Cell.size  Cell.shape  Marg.adhesion  Epith.c.size  \
0  1000025             5          1           1              1             2   
1  1002945             5          4           4              5             7   
2  1015425             3          1           1              1             2   
3  1016277             6          8           8              1             3   
4  1017023             4          1           1              3             2   

   Bare.nuclei  Bl.cromatin  Normal.nucleoli  Mitoses  Class  
0          1.0            3                1        1      0  
1         10.0            3                2        1      0  
2          2.0            3                1        1      0  
3          4.0            3                7        1      0  
4          1.0            3                1        1      0

In [6]:
X=df.values[:, 1:-1]
y=df.values[:, -1]
np.unique(y, return_counts=True)

(array([0., 1.]), array([444, 239]))

In [8]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=.5, random_state=0)

In [9]:
xtrain_pos=xtrain[ytrain==1, :]

In [10]:
dist_test_mincov=MinCovDet(random_state=0).fit(xtrain_pos).mahalanobis(xtest)
dist_test_cov=EmpiricalCovariance().fit(xtrain_pos).mahalanobis(xtest)

In [11]:
dist_test_mincov

array([ 14.06449152,  15.00904462,   7.15577778,  14.76228757,
        19.08367395,  17.18461552,  13.49433738,  48.49929321,
        15.43676311,  18.90783032,  14.88256346,  12.90706676,
       114.56268079,  15.00904462,  18.100182  ,  38.32792939,
        14.73462036,  26.4769359 ,  35.82185147,  13.02342282,
        15.00904462,  13.43733625,  14.75987098,  15.39769414,
         9.74831224,   2.67827321,  14.58274724,  45.7813721 ,
        13.21418778,  18.4701185 ,  19.08367395,  29.53226315,
        35.56467455,  15.2906684 ,  14.11813178,  15.2906684 ,
         8.90609868,   4.4221947 ,  14.11813178,  18.98621561,
        12.35145945,  17.22296755,  18.04691696,  15.04312737,
        19.08367395,  15.55634486,  18.50148603,   6.57103913,
        13.67401471,  13.21418778,  16.9814909 ,  12.55898207,
        12.59415437,  12.31483824,  13.02342282,  12.52692585,
        13.98603425,  14.6805946 ,  10.13250502,  17.75879088,
        19.40225998,  17.44284425,  17.15865501,  15.39

In [12]:
dist_test_cov

array([13.81674499, 13.85972718,  4.51233652, 13.24485401, 18.14712389,
       14.65967746, 11.12657919, 12.68322688, 15.65123616, 17.6577248 ,
        5.63650512, 11.69508329, 17.52414374, 13.85972718, 15.78673287,
       21.4185189 ,  6.73116067, 11.16086295, 13.13641472, 12.92582703,
       13.85972718, 12.44219804,  8.27941558, 14.43884433,  6.76139749,
        1.75860408, 12.17869839, 20.24435359, 12.24384295,  5.33075668,
       18.14712389, 15.65017895,  7.63851642, 13.88628595, 13.15218387,
       13.88628595,  3.94006912,  3.96512587, 13.15218387, 11.92970459,
       11.2130706 , 14.93072875, 18.79753361, 15.01047837, 18.14712389,
       12.99554435, 18.46899364,  6.43391539, 12.7428228 , 12.24384295,
       10.21884396, 12.16090728,  8.27411749, 12.02395341, 12.92582703,
       10.6431334 , 11.02921139,  6.261665  ,  8.55937586, 13.75891842,
       17.77400164, 16.68763717, 15.64098402, 14.43884433, 13.88628595,
       17.77400164, 17.77400164, 13.88628595,  5.2786029 , 19.01

In [14]:
from scipy.stats import chi2
crit_distance=chi2.ppf((1-0.01), df=xtrain_pos.shape[1])

In [15]:
print(np.sum(dist_test_cov>crit_distance))
print(np.sum(dist_test_mincov>crit_distance))

7
47
